### ISSUE TITLE
ValueError while running the app.

### ISSUE THREAD

**Issue by reshinthadithyan** [huggingface/datasets-tagging#1]
Hello, tried to run the app from Windows. Got, 
ValueError: not enough values to unpack (expected 4, got 1)
Traceback:
File "g:\python\lib\site-packages\streamlit\script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "G:\Work Related\hf\dtagger\datasets-tagging\tagging_app.py", line 164, in <module>
    existing_tag_sets = load_existing_tags()
File "G:\Work Related\hf\dtagger\datasets-tagging\tagging_app.py", line 135, in load_existing_tags
    _, did, cid, _ = fname.split('/')

**Comment by gbt111** [comment]
> Hello, tried to run the app from Windows. Got, 
> 
> ValueError: not enough values to unpack (expected 4, got 1)
> 
> Traceback:
> 
> File "g:\python\lib\site-packages\streamlit\script_runner.py", line 332, in _run_script
> 
>     exec(code, module.__dict__)
> 
> File "G:\Work Related\hf\dtagger\datasets-tagging\tagging_app.py", line 164, in <module>
> 
>     existing_tag_sets = load_existing_tags()
> 
> File "G:\Work Related\hf\dtagger\datasets-tagging\tagging_app.py", line 135, in load_existing_tags
> 
>     _, did, cid, _ = fname.split('/')

**Comment by reshinthadithyan** [comment]
Closing as this is resolved.

**Comment by albertvillanova** [comment]
Due to code refactoring, this issue no longer exists.
