### ISSUE TITLE
streamlit app not working

### ISSUE THREAD

**Issue by bhavitvyamalik** [huggingface/datasets-tagging#14]
I'm running into an error everytime I start my streamlit app:
`ModuleNotFoundError: No module named 'datasets.utils.metadata'`

I checked `tagging_app.py` and found that it's making a few  imports from `datasets.utils.metadata` and unfortunately no such file exists in current `datasets` master branch. As a workaround I rolled it back to a particular commit after cloning the repository. 

One can follow these steps (temporary fix):
1) `git clone https://github.com/huggingface/datasets-tagging.git`
2) `cd datasets-tagging`
3) `pip install -r requirements.txt`
4) `git reset --hard 927d44346b12fac66e97176608c5aa81843a9b9a` (takes you back to the commit when it was working fine)
5) `streamlit run tagging_app.py`

**Comment by bhavitvyamalik** [comment]
@theo-m please let me know if it looks good. Maybe we can also add the link to this issue on README so that any new/existing contributor can fix it before hand only. After the fix we can remove it from there.

**Comment by albertvillanova** [comment]
This was already fixed.
