### ISSUE TITLE
Empty module name error

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/datasets-tagging#3]
I encounter this error when running `streamlit run tagging_app.py`:

```python
ValueError: Empty module name

Streamlit encountered an error while caching the body of get_info_dicts(). This is likely due to a bug in /home/patrick/python_bin/datasets/utils/file_utils.py near line 204:


from .. import SCRIPTS_VERSION

version = version or os.getenv("HF_SCRIPTS_VERSION", SCRIPTS_VERSION)
```

The problem is this import line in `datasets`: 
https://github.com/huggingface/datasets/blob/f9f830ed04750514b2fb34a0cad4946e95736c01/src/datasets/utils/file_utils.py#L204

I can be easily resolved by just setting `SCRIPTS_VERSION = "master"` and deleting the import, but that's not really what we want.
I have `datasets` not installed via pip, but I've cloned the repo and then added the path to my PYTHONPATH...Not sure whether it's only me who is having this problem...

@yjernite @lhoestq

**Comment by albertvillanova** [comment]
Due to code refactoring, this issue no longer exists.
